apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-behavior-backend
  namespace: web-behavior
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-behavior-backend
  template:
    metadata:
      labels:
        app: web-behavior-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/dinerozz/web-behavior:master
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: DB_NAME
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: DB_SSLMODE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: web-behavior-config
                  key: REDIS_PORT
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: web-behavior-secret
                  key: DB_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-behavior-secret
                  key: JWT_SECRET
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: web-behavior-secret
                  key: TELEGRAM_BOT_TOKEN
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-behavior-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5555
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 5