# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-behavior-backend-service
  namespace: web-behavior
spec:
  selector:
    app: web-behavior-backend
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 30081
  type: NodePort