ALTER TABLE user_behaviors
ALTER COLUMN updated_at TYPE TIMESTAMP;

ALTER TABLE user_behaviors
ALTER COLUMN created_at TYPE TIMESTAMP;

ALTER TABLE user_behaviors
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_behaviors
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;